### ISSUE TITLE
V3 API

### ISSUE THREAD

**Issue by chriseldredge** [themotleyfool/NuGet.Lucene#27]

**Comment by twenzel** [comment]
Any progress for V3 support?

**Comment by chriseldredge** [comment]
No plans to work on V3.

**Comment by chriseldredge** [comment]
Closing. The V3 API is a dramatic departure from V2. At this time dnx/aspnet vnext/whatever support using API V2. At this time there is no clear spec for how ecosystem developers to create compliant V3 APIs besides reading the source code for NuGet Gallery or related projects.
