### ISSUE TITLE
Async Tasks (Question)

### ISSUE THREAD

**Issue by coommark** [themotleyfool/NuGet.Lucene#30]
Is it possible to index and search asynchronously? Like async Task<SomeObjec> Index() then use the await keyword? Can't find any sample online. Or do I need to use a contrib for this? Thanks.

**Comment by chriseldredge** [comment]
This project uses Lucene.Net.Linq to store metadata for a NuGet Package Repository. Is your question related to NuGet.Lucene or more generally to Lucene.Net.Linq?

**Comment by chriseldredge** [comment]
Please reopen if you can more clearly rephrase your question.
