### ISSUE TITLE
Unable to push packages anonymously

### ISSUE THREAD

**Issue by twenzel** [themotleyfool/NuGet.Lucene#33]
I've created an empty ASP.NET application, added your NuGet package and deployed it to IIS.
The service works fine, available packages will be listed using `nuget.exe list`.
But when I'm trying to push a new package using `NuGet.exe push "..\bin\Packages\CHG.iCLASSFW.Core.15.2.1.10.nupkg" -s http://bobthebuilder/packages2/ mykey`
the service requests for a username and password.:
`Please provide credentials for: http://bobthebuilder/packages2/api/odata/ `

I've already set the app setting `<add key="NuGet.Lucene.Web:allowAnonymousPackageChanges" value="true"/>`.

What I'm doing wrong?

**Comment by chriseldredge** [comment]
Which version of NuGet.Lucene are you using?

**Comment by twenzel** [comment]
The latest 2.9.4.

**Comment by twenzel** [comment]
I've downloaded the source code. I guess you've rewritten some parts. Owin, Autofac etc.
Can you give me short introduction how to setup an IIS website with the new code?

**Comment by twenzel** [comment]
Problem solved.
I've defined my global API key with "apiKey" app setting instead of "localAdministratorApiKey". So the service did not recognized my key and returned a HttpStatusCode.Unauthorized with the phrase "Invalid API-Key". 
Unfortunately the nuget client won't show/handle this error correctly.

**Comment by chriseldredge** [comment]
Glad you got it working. The intended design is that when allowAnonymousPackageChanges is true that no api key is needed at all. Did you get that to work correctly or did you work around it by setting localAdministratorApiKey?

To answer your other question, to use the NuGet.Lucene.Web 3.0.0-beta packages, you would create an empty asp.net application, and create a OWIN Startup class that subclasses the one provided in NuGet.Lucene.Web. There's a sample OWIN self-hosted project at https://github.com/themotleyfool/NuGet.Lucene/tree/master/source/NuGet.Lucene.Web.OwinHost.Sample, and [Klondike](https://github.com/themotleyfool/Klondike/tree/master/src/Klondike.WebHost) is another example of how to embed this library in a web project.

**Comment by twenzel** [comment]
I've worked around it by setting the localAdministratorApiKey.
