### ISSUE TITLE
Not working with VS2015 (RC)

### ISSUE THREAD

**Issue by twenzel** [themotleyfool/NuGet.Lucene#34]
Unfortunately Visual Studio 2015 calls a slightly different URL to retrieve NuGet packages.

`http://localhost:9001/api/odata/Packages(Id='DevExpress.Web.ASPxSpreadsheet',Version='14.2.7.0')/Id`
The `/Id`suffix is the part which confuses me a little bit.

**Comment by chriseldredge** [comment]
curl http://www.nuget.org/api/v2/Packages\(Id=\'Nuget.Core\',Version=\'2.8.3\'\)/Id
    <?xml version="1.0" encoding="utf-8"?>
    <d:Id xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
      Nuget.Core
    </d:Id>

I guess this new request validates that a repository has a package and gets the canonical case-spelling of the package ID.

**Comment by twenzel** [comment]
The problem is if this request failes VS will not retrieve the package from this package source.

**Comment by chriseldredge** [comment]
I think I'm close to understanding how to fix this.

What specific action are you invoking in Visual Studio 2015 RC? Package restore? Install? Using Package Manager Console or GUI?

**Comment by twenzel** [comment]
I'm trying a package restore from the GUI.

**Comment by twenzel** [comment]
Your recent commit (e65d1a00942c9a11aa1ad4bb2282027c46784e93) solved this issue.
