### ISSUE TITLE
Unable to find a version of 

### ISSUE THREAD

**Issue by VGBenjamin** [themotleyfool/NuGet.Lucene#35]
Hello,

I try to install the nuget package for the web server but I have the following issue:

Install-Package : Updating 'Microsoft.AspNet.WebApi.WebHost 5.0.0' to 'Microsoft.AspNet.WebApi.WebHost 4.0.20710.0' failed. Unable to find a version of 
'AspNet.WebApi.HtmlMicrodataFormatter' that is compatible with 'Microsoft.AspNet.WebApi.WebHost 4.0.20710.0'.
At line:1 char:1
+ Install-Package NuGet.Lucene.Web
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
Regards,

BEnjamin V

**Comment by chriseldredge** [comment]
Sorry for taking so long to respond. Were you installing NuGet.Lucene.Web into a new project or one that is already using Microsoft.AspNet.WebApi.WebHost?

**Comment by chriseldredge** [comment]
Closing. If you continue to experience problems using NuGet.Lucene.Web 3.0.0 or later let me know.
