### ISSUE TITLE
New NuGet package on the way?

### ISSUE THREAD

**Issue by battenworks** [themotleyfool/NuGet.Lucene#37]
While I can see activity on the project, the latest package that can be downloaded from nuget.org is dated March, 2014. That version has an issue where the VS UI calls $batch with the POST method (when a large amount of packages are involved), and a 405 is returned.
Seems the code has been fixed, but I was wondering if you had any plans to repackage the new code for fetch on nuget.org.

**Comment by chriseldredge** [comment]
I'm way behind on an official release, but in the meantime there are relatively stable builds you can use on AppVeyor

Klondike app builds: https://ci.appveyor.com/project/chriseldredge/klondike/build/artifacts

NuGet.Lucene packages feed: https://ci.appveyor.com/nuget/nuget-lucene-gsxts1jkyeml
