### ISSUE TITLE
Repository not accessable from VS2015 Update 1

### ISSUE THREAD

**Issue by twenzel** [themotleyfool/NuGet.Lucene#41]
The repository is not accessable anymore after installing Update 1 for VS2015.

Error: The remote server returned an error: (503) Server Unavailable.

**Comment by chriseldredge** [comment]
Are you able to access Klondike from a web browser? Please check `~/App_Data/Logs` for additional hints.

**Comment by twenzel** [comment]
I'm not using Klondike, but the Website is accessable. It's also still possible to access the repository from VS2013.

**Comment by twenzel** [comment]
Found the problem on my side. Sorry.
