### ISSUE TITLE
Allow sending DefaultCredentials to Mirrored Repo During Package Download

### ISSUE THREAD

**Issue by bbattah** [themotleyfool/NuGet.Lucene#42]
We have a Klondike nuget server running 2.0.0 locally.  This system runs with authentication enabled on the web-site.   We stood up an additional Klondike 2.0.0 instance to mirror that nuget feed in another geography.  The mirror can enumerate packages from the source but fails to respond to a 401 auth challenge when downloading any discovered packages.

It appears this is because of the use of System.Net.Http.HttpClient in the LucenePackageRepository of the NuGet.Lucene project.  Making the following change has cleared up the problem:

 `protected virtual System.Net.Http.HttpClient CreateHttpClient()
        {
            return new System.Net.Http.HttpClient();
        }`

Changed to:
` protected virtual System.Net.Http.HttpClient CreateHttpClient()
        {
            return new System.Net.Http.HttpClient(new System.Net.Http.HttpClientHandler() { UseDefaultCredentials = true });
        }`

**Comment by chriseldredge** [comment]
Fixed by 18183ba888f68ba2735be446f17438050eddb66e
