### ISSUE TITLE
NuGet.Lucene is terribly slow when dealing with OctopusDeploy packages

### ISSUE THREAD

**Issue by alex-davidson** [themotleyfool/NuGet.Lucene#49]
We use Klondike to provide a package feed for an Octopus server, in addition to regular NuGet packages.

Searches and fetches against the NuGet feed seem extremely slow, even with only a few thousand packages stored. Octopus frequently takes several minutes to find package versions. During this time, the Klondike process is maxing out the CPU.

Applying the Visual Studio standalone profiler reveals that most of the time (97%) is spent in LuceneQueryExecutorBase.EnumerateHits (strictly, in MoveNext()). Applying Luke v4 to the index reveals a huge number of stored fields, one for each file in the package.
Our Octopus packages are not large. Most are significantly smaller than 100MB and contain only a few thousand files.

The issue appears to be that the LucenePackage object's properties are individually stored in the index. Rehydrating an object from many stored fields is a slow operation in Lucene. Our own approach to handling this sort of thing is to use a single JSON field to store the object and keep the other fields index-only. I'm not sure how this mght translate to Lucene.Net.Linq's way of doing things though.

**Comment by chriseldredge** [comment]
If you have large packages with many files, and don't need to search based on file paths, you can disable indexing of files setting [ignorePackageFiles](https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.WebHost/Settings.config#L112) to true, then rebuilding your index.

Storing complex metadata in a JSON field is an interesting approach, but has the tradeoff of limiting options for searching and aggregating based on that metadata.

**Comment by alex-davidson** [comment]
Thanks, that's had a huge effect on performance!
This explains why the server's memory usage was so much higher than we expected, too. It's much more reasonable now.

**Comment by alex-davidson** [comment]
Since this is by design and there's a workaround for this use case, I'll close this issue.
